### PR TITLE
add support for hung pcm process 

### PR DESCRIPTION
**Pull request by sdetweil**

### CODE REVIEW

**Comment by ashishsc** [comment]
Hey @evancohen This has been here for awhile, do you want to take a look?

**Comment by evancohen** [comment]
There is a real issue with the underlying recording library. When using `arecord`, the process dies silently, but the binary output (chunk size) reliably changes at the time of the crash.

The ideal fix here would be to monitor chunk size, restart the process when it crashes, and repipe the audio internally.

**Comment by sdetweil** [comment]
>The ideal fix here would be to monitor chunk size, restart the process when it crashes, and repipe the audio internally.

working on it..

**Comment by sdetweil** [comment]
see PR 93 which handles it as suggested... this one will be closed... wrong solution

**Pull request closed without merging**
